### ISSUE TITLE
Можно ввести отрицательное число в поле "weight" и "price"

### ISSUE THREAD

**Issue by demgerall** [rrodar/kscksdm#2]
В поле ввода данных для значения веса и цены камней можно ввести отрицательное число (вес камней не может быть отрицательным в принципе), что впоследствии влияет на  значение общего веса, выводя его неправильным.
![1](https://user-images.githubusercontent.com/107266948/173103066-b94d4bfb-4e07-4871-854b-3ba095859efe.jpg)

**Comment by rrodar** [comment]
Код исправлен
![image](https://user-images.githubusercontent.com/55837186/173107029-ea4f58d9-d213-410b-9a01-c1b9e4f40aa5.png)
![image](https://user-images.githubusercontent.com/55837186/173107059-efb46f88-61e2-45e2-a510-9ebc75609673.png)
